[workspace]

resolver = "3"

members = [
    "crates/math",
    "crates/string",
    "crates/greedy",
    "crates/sorting",
    "crates/searching",
    "crates/navigation",
    "crates/big_integer",
    "crates/backtracking",
    "crates/number_theory",
    "crates/data_structures",
]

[workspace.dependencies]

# crates
sorting = { path = "./crates/sorting" }
data_structures = { path = "./crates/data_structures" }

# dependencies
rand = { version = "0.9"}
quickcheck = "1.0"
quickcheck_macros = "1.0"
num-bigint = { version = "0.4" }
num-traits = { version = "0.2" }
