[workspace]

resolver = "3"

members = [
    "crates/sorting",
    "crates/string",
    "crates/searching",
    "crates/backtracking",
    "crates/number_theory",
    "crates/data_structures", "crates/big_integer",
]

[workspace.dependencies]

# crates
sorting = { path = "./crates/sorting" }
data_structures = { path = "./crates/data_structures" }

# dependencies
rand = { version = "0.9"}
quickcheck = "1.0"
quickcheck_macros = "1.0"
